### ISSUE TITLE
Sorting imported functions from a module alphabetically

### ISSUE THREAD

**Issue by robstewart57** [haskell/haskell-mode#206]
The `haskell-sort-imports.el` is great! It re-orders imported modules according to their namespace. What would also be great is the ability to re-order the imported functions from a module E.g.

    import Data.Text (pack)
    import Data.Map (null,member)

would be re-ordered, both in module namespaces and with function names as:

    import Data.Map (member,null)
    import Data.Text (pack)

**Comment by gracjan** [comment]
This issue has not seen activity for a very long time. Is this still something we should be concerned about?

**Comment by geraldus** [comment]
I think we can contact `stylish-buffer` author and ask for a customization feature such as stylize only imports, do not stylize records, and etc. (through `.stylish-haskell.yaml` or/and command line args) or even provide a PR for this stuff.  But it looks like Jasper Van der Jeugt is quite busy right now.

**Comment by geraldus** [comment]
Oh, looks like this is not relevant anymore, because it is already possible to make such configuration through `.stylish-haskell.yaml`:

```yml
# stylish-haskell configuration file
# ==================================

# The stylish-haskell tool is mainly configured by specifying steps. These steps
# are a list, so they have an order, and one specific step may appear more than
# once (if needed). Each file is processed by these steps in the given order.
steps:
  # Convert some ASCII sequences to their Unicode equivalents. This is disabled
  # by default.
  # - unicode_syntax:
  #     # In order to make this work, we also need to insert the UnicodeSyntax
  #     # language pragma. If this flag is set to true, we insert it when it's
  #     # not already present. You may want to disable it if you configure
  #     # language extensions using some other method than pragmas. Default:
  #     # true.
  #     add_language_pragma: true

  # Import cleanup
  - imports:
      # There are different ways we can align names and lists.
      #
      # - global: Align the import names and import list throughout the entire
      #   file.
      #
      # - file: Like global, but don't add padding when there are no qualified
      #   imports in the file.
      #
      # - group: Only align the imports per group (a group is formed by adjacent
      #   import lines).
      #
      # - none: Do not perform any alignment.
      #
      # Default: global.
      align: global

  # Language pragmas
  - language_pragmas:
      # We can generate different styles of language pragma lists.
      #
      # - vertical: Vertical-spaced language pragmas, one per line.
      #
      # - compact: A more compact style.
      #
      # - compact_line: Similar to compact, but wrap each line with
      #   `{-#LANGUAGE #-}'.
      #
      # Default: vertical.
      style: vertical

      # stylish-haskell can detect redundancy of some language pragmas. If this
      # is set to true, it will remove those redundant pragmas. Default: true.
      remove_redundant: true

  # Align the types in record declarations
  - records: {}

  # Replace tabs by spaces. This is disabled by default.
  # - tabs:
  #     # Number of spaces to use for each tab. Default: 8, as specified by the
  #     # Haskell report.
  #     spaces: 8

  # Remove trailing whitespace
  - trailing_whitespace: {}

# A common setting is the number of columns (parts of) code will be wrapped
# to. Different steps take this into account. Default: 80.
columns: 80

# Sometimes, language extensions are specified in a cabal file or from the
# command line instead of using language pragmas in the file. stylish-haskell
# needs to be aware of these, so it can parse the file correctly.
#
# No language extensions are enabled by default.
language_extensions:
  - TemplateHaskell
  - QuasiQuotes
  - TypeFamilies
  - MultiParamTypeClasses
  - FlexibleContexts
  - OverloadedStrings
  - NoImplicitPrelude
  - CPP
  - GADTs
  - GeneralizedNewtypeDeriving
  - EmptyDataDecls
  - NoMonomorphismRestriction
  - DeriveDataTypeable
  - ViewPatterns
  - TupleSections
  - RecordWildCards
```
